main: net.tytonidae.quickstack.Main
name: QuickStack
version: 2.0
author: tytonidae
description: Adds functionality for automatic item collapse from inventory into nearby chests

commands: 
  stack:
    description: Combine all possible items from inventory with those in nearby chests
    permission: quickstack.stack
    usage: /stack
  qsradius:
    description: Adjust the QuickStack search radius for chests
    permission: quickstack.adjustradius
    usage: "Usage: /qsradius [radius]"
    
permissions:
  quickstack.*:
    description: Gives access to all QuickStack commands.
    children:
      quickstack.stack: true
      quickstack.adjustradius: true
  quickstack.stack:
    description: Allows holders to quickly stack items into nearby chests
    default: true
  quickstack.adjustradius:
    description: Allows holders to adjust the QuickStack search radius for chests
    default: op